//#include "pch.h"
#include "first_xll_macros.h"
#include "af_xloper.h"

// #define AF_EXCLUDE_DEFAULT_FUNCTIONS 
// Declaring 
AF_DECLARE_XLL("Autotelica XLL Testing");

// AF_DECLARE_EXCEL_FUNCTION
// AF_DECLARE_EXCEL_VOLATILE_FUNCTION
// AF_DECLARE_EXCEL_NAMED_FUNCTION
// AF_DECLARE_EXCEL_VOLATILE_NAMED_FUNCTION

// AF_DECLARE_QD_EXCEL_FUNCTION
// AF_DECLARE_QD_EXCEL_VOLATILE_FUNCTION

// AF_DECLARE_LAMBDA_EXCEL_FUNCTION
// AF_DECLARE_LAMBDA_EXCEL_VOLATILE_FUNCTION
// AF_DECLARE_QD_LAMBDA_EXCEL_FUNCTION
// AF_DECLARE_QD_LAMBDA_EXCEL_VOLATILE_FUNCTION
